# {# pkglts, travis
# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"

#sudo: required

addons:
  apt:
    packages:
    - libboost-python-dev

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
 # - apt-get update -qq
 # - apt-get install libboost-python-dev
 - pip install -r requirements.txt
 - pip install -r dvlpt_requirements.txt
 - pip install --upgrade git+https://github.com/openalea/deploy#egg=OpenAlea.Deploy
 - pip install --upgrade git+https://github.com/openalea/sconsx#egg=OpenAlea.SConsX

# command to run tests, e.g. python setup.py test
script:
 - scons
 - python setup.py install
 - ls -R /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/oacpp-0.1.0-py2.7-linux-x86_64.egg/
 - pwd
 - export LD_LIBRARY_PATH=/home/travis/virtualenv/python2.7.9/lib/lib/
 - nosetests


# #}
