# {# pkglts, travis
# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"

addons:
  apt:
    packages:
    - libboost-python-dev

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
 - pip install -r requirements.txt
 - pip install -r dvlpt_requirements.txt
 - pip install --upgrade git+https://github.com/openalea/deploy#egg=OpenAlea.Deploy
 - pip install --upgrade git+https://github.com/openalea/sconsx#egg=OpenAlea.SConsX

# command to run tests, e.g. python setup.py test
script:
 - scons
 - python setup.py install
 - ls -R
 - python explore.py
 #- export LD_LIBRARY_PATH=$VIRTUAL_ENV/lib/lib/
 - export LD_LIBRARY_PATH=./build/lib/lib
 - nosetests


# #}
after_success:
