# -*-python-*-

Import("env")

py_dir = '..//oacpp' if '' else '../oacpp'

# Build wrappers as shared libraries
# First wrapper
env1 = env.Clone()

sources = env1.ALEAGlob('*.cpp')
target = "_oacpp"
lib = ["oacpp"]

env1.AppendUnique(LIBS=lib)

env1.ALEAWrapper(py_dir, target, sources)

